# apiVersion: kubedb.com/v1alpha2
# kind: Postgres
# metadata:
#   name: demo-pg-13
#   namespace: demo
# spec:
#   version: "13.1"
#   # version: "12.5"
#   # version: "11.10"
#   # version: "10.15"
#   # version: "9.6.20"
#   replicas: 3
#   standbyMode: Hot
#   clientAuthMode: cert
#   # sslMode: verify-full
#   storageType: Durable
#   tls:
#     issuerRef:
#       apiGroup: cert-manager.io
#       name: postgres-ca-issuer
#       kind: Issuer
#   storage:
#     storageClassName: "standard"
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#   terminationPolicy: WipeOut
#   podTemplate: 
#     spec: 
#       resources:
#         limits:
#           cpu: 250m
#           memory: 1Gi
#         requests:
#           cpu: 250m
#           memory: 1Gi

# ---

# apiVersion: kubedb.com/v1alpha2
# kind: Postgres
# metadata:
#   name: demo-pg-12
#   namespace: demo
# spec:
#   # version: "13.1"
#   version: "12.5"
#   # version: "11.10"
#   # version: "10.15"
#   # version: "9.6.20"
#   replicas: 3
#   standbyMode: Hot
#   clientAuthMode: scram
#   # sslMode: verify-full
#   storageType: Durable
#   # tls:
#   #   issuerRef:
#   #     apiGroup: cert-manager.io
#   #     name: postgres-ca-issuer
#   #     kind: Issuer
#   storage:
#     storageClassName: "standard"
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#   terminationPolicy: WipeOut
#   podTemplate: 
#     spec: 
#       resources:
#         limits:
#           cpu: 250m
#           memory: 1Gi
#         requests:
#           cpu: 250m
#           memory: 1Gi

---
# apiVersion: kubedb.com/v1alpha2
# kind: Postgres
# metadata:
#   name: demo-pg-11
#   namespace: demo
# spec:
#   # version: "13.1"
#   # version: "12.5"
#   version: "11.10"
#   # version: "10.15"
#   # version: "9.6.20"
#   replicas: 3
#   standbyMode: Hot
#   clientAuthMode: scram
#   # sslMode: verify-full
#   storageType: Durable
#   # tls:
#   #   issuerRef:
#   #     apiGroup: cert-manager.io
#   #     name: postgres-ca-issuer
#   #     kind: Issuer
#   storage:
#     storageClassName: "standard"
#     accessModes:
#     - ReadWriteOnce
#     resources:
#       requests:
#         storage: 1Gi
#   terminationPolicy: WipeOut
#   podTemplate: 
#     spec: 
#       resources:
#         limits:
#           cpu: 250m
#           memory: 1Gi
#         requests:
#           cpu: 250m
#           memory: 1Gi
---
apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: demo-pg-10
  namespace: demo
spec:
  # version: "13.1"
  # version: "12.5"
  # version: "11.10"
  version: "10.15"
  # version: "9.6.20"
  replicas: 3
  standbyMode: Hot
  # clientAuthMode: scram
  sslMode: verify-full
  storageType: Durable
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      name: postgres-ca-issuer
      kind: Issuer
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  podTemplate: 
    spec: 
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi
---

apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: demo-pg-9
  namespace: demo
spec:
  # version: "13.1"
  # version: "12.5"
  # version: "11.10"
  # version: "10.15"
  version: "9.6.20"
  replicas: 3
  standbyMode: Hot
  # clientAuthMode: scram
  sslMode: verify-full
  storageType: Durable
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      name: postgres-ca-issuer
      kind: Issuer
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  podTemplate: 
    spec: 
      resources:
        limits:
          cpu: 250m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 1Gi
---